name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      
      - name: Build Protoc Docker container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: protoc.dockerfile
          tags: tinkar-schema-protoc:latest

      - name: Build C# Docker container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: protoc.dockerfile
          tags: tinkar-schema-csharp:latest
      
  # container-test-job:
  #     container:
  #     image: node:18
  #     env:
  #       NODE_ENV: development
  #     ports:
  #       - 80
  #     volumes:
  #       - my_docker_volume:/volume_mount
  #     options: --cpus 1