name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'adopt'

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      
      - name: Build Protoc Docker container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: protoc.dockerfile
          tags: tinkar-schema-protoc:latest
          #outputs: type=docker,dest=/tmp/protocimage.tar

      - name: Build C sharp Docker container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: csharp.dockerfile
          tags: tinkar-schema-csharp:latest
          #outputs: type=docker,dest=/tmp/csharpimage.tar

      - name: make directory for protoc generated code
        run: |
          mkdir -p src/main/java/generated

      - name: make directory for csharp generated code
        run: |
          mkdir -p src/main/csharp-generated

      - name: test run in container
        run: |
          docker run -v $HOME/src/main/java/dev/ikm/tinkar/schema:$HOME/src/main/java/dev/ikm/tinkar/schema/ --rm tinkar-schema-protoc:latest \
            mkdir -p $HOME/src/main/java/dev/ikm/tinkar/schema/; \
            protoc -I $HOME $HOME/Tinkar.proto  --java_out=$HOME/src/main/java/dev/ikm/tinkar/schema/; \
            pwd; \
            ls -R $HOME/src/main/java/dev/ikm/tinkar/schema/
      
      - name: print std err
        run: |
          echo ${{ steps.fails.outputs.stderr }}
      
      - name: list java code
        run: |
          ls $HOME/src/main/java/dev/ikm/tinkar/schema/

      - name: build java code
        run: |
          ./mvnw clean install \
              --batch-mode \
              -e \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -Dmaven.build.cache.enabled=false \
              -PcodeQuality
